[+] add(testing): run tests script added in pre-commit script

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -4,6 +4,10 @@ RESET="\033[0m"
 BOLD="\033[1m"
 GREEN="\033[32m"
 YELLOW="\033[33m"
+RED="\033[31m"
+
+TEST_SCRIPT_DIR="$(dirname "$(realpath "$0")")"
+TEST_SCRIPT="$TEST_SCRIPT_DIR/run_tests.sh"
 
 files=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) ! -path '*/.*' ! -path './build/*')
 
@@ -18,6 +22,16 @@ else
 fi
 
 if [ $? -ne 0 ]; then
-    echo "Formatting failed. Please fix the issues before pushing."
+    echo -e $RED "Formatting failed. Please fix the issues before pushing." $RESET
     exit 1
 fi
+
+echo -e $BOLD$GREEN " >> Running tests..." $RESET
+"$TEST_SCRIPT"
+
+if [ $? -ne 0 ]; then
+    echo -e $RED "Tests failed. Please fix the issues before pushing." $RESET
+    exit 1
+fi
+
+echo -e $BOLD$GREEN "All checks passed successfully!" $RESET
